use crate::ai::agent::SuggestedLoggingId;
use serde::{Deserialize, Serialize};

pub mod manager;
pub mod view;
pub use manager::AIFactManager;
pub use view::{AIFactView, AIFactViewEvent};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct AIMemory {
    #[serde(default)]
    pub name: Option<String>,
    pub content: String,
    // Deprecated: This field is no longer used and will be removed in the future.
    #[serde(default)]
    pub is_autogenerated: bool,
    /// If this rule was created from a suggested rule, record the suggestion's logging_id
    /// so we can suppress re-surfacing the same suggestion in future responses.
    #[serde(default)]
    pub suggested_logging_id: Option<SuggestedLoggingId>,
}
